apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash-test
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: logstash-test
    spec:
      containers:
      - image: docker.elastic.co/logstash/logstash:5.6.4
        name: logstash-test
        ports:
        - name: logstash
          containerPort: 5044
          protocol: TCP
      nodeSelector:
        kube-aws.coreos.com/role: worker
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-test
  namespace: default
  labels:
    app: logstash-test
spec:
  type: LoadBalancer
  selector:
    app: logstash-test
  ports:
  - name: logstash
    port: 5044
    targetPort: 5044
    protocol: TCP
