apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  name: logstash-test
  namespace: default
data:
  logstash.conf: |-
    input {
      tcp {
        port => 5044
        codec => json
      }
    }
    output {
      elasticsearch {
        hosts => "elasticsearch-logging.elasticsearch:9200"
        index => "test-%{+YYYY.MM.dd}"
        document_type => "%{[@metadata][type]}"
        sniffing => false
      }
    }
  logstash.yml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.enabled: false

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash-test
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: logstash-test
    spec:
      containers:
      - image: docker.elastic.co/logstash/logstash:5.5.0
        name: logstash-test
        ports:
        - name: logstash
          containerPort: 5044
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          readOnly: true
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
          readOnly: true
        args:
        - -f
        - /usr/share/logstash/pipeline/logstash.conf
        resources:
          limits:
            memory: 2Gi
            cpu: "200m"
          requests:
            memory: 2Gi
            cpu: "200m"
      volumes:
      - name: pipeline
        configMap:
          name: logstash-test
          items:
          - key: logstash.conf
            path: logstash.conf
      - name: config
        configMap:
          name: logstash-test
          items:
          - key: logstash.yml
            path: logstash.yml
      nodeSelector:
        kube-aws.coreos.com/role: worker
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-test
  namespace: default
  labels:
    app: logstash-test
spec:
  type: LoadBalancer
  selector:
    app: logstash-test
  ports:
  - name: logstash
    port: 5044
    targetPort: 5044
    protocol: TCP
